### ISSUE TITLE
I want to use Microsoft Oauth is it posibble ?

### ISSUE THREAD

**Issue by madhan-srinivasan-21** [gocd-contrib/google-oauth-authorization-plugin#233]
i want use Microsoft instead of Google, there is any possibility

**Comment by chadlwilson** [comment]
Not with this plugin, no.

Not sure what you mean by "Microsoft" (Azure AD? Microsoft Login?) but there is no plugin I am aware of for any of those, nor is there a "generic" OAuth2 plugin.
