### ISSUE TITLE
Session length too short

### ISSUE THREAD

**Issue by wraithy** [gocd-contrib/google-oauth-authorization-plugin#5]
I've found that in the build bundled with GoCD 18.2 I have to auth myself every time I switch to the GoCD tab in my browser. I probably do this once every two hours or so.

It doesn't look like there's any way to configure this. Personally I'd rather only have to log in once a month.
Was the short session length a conscious decision? Or could we increase that/add a configuration option?

**Comment by michaelbannister** [comment]
Me too. I haven't tried yet but I _suspect_ this corresponds to the 'reauthentication interval' time described in https://docs.gocd.org/current/configuration/dev_authentication.html which can be controlled by setting system property `go.security.reauthentication.interval`

**Comment by bdpiparva** [comment]
@wraithy --- @michaelbannister is right. You can increase the reauthentication interval as mentioned in https://docs.gocd.org/current/configuration/dev_authentication.html

**Comment by michaelbannister** [comment]
@bdpiparva this actually doesn't seem to work.
I can see from /go/api/support that the system property go.security.reauthentication.interval=86400 is set but I'm still getting booted back to login at least once an hour, possibly even every half hour, suggesting that this setting isn't taking effect.
[api-support.txt](https://github.com/gocd-contrib/google-oauth-authorization-plugin/files/1883303/api-support.txt)
