### ISSUE TITLE
Extension incompatibility detected between plugin and gocd

### ISSUE THREAD

**Issue by erIamshivani** [gocd-contrib/google-oauth-authorization-plugin#54]
Hi, I am absolute beginner to GoCD. I was trying to use the plugin `google-oauth-authorization-plugin` and I am getting following error message while adding plugin:

`Extension incompatibility detected between plugin(google.oauth.login) and GoCD:
  Extension(s) [authentication] used by the plugin is not supported. GoCD Supported extensions are [analytics, artifact, authorization, notification, task, configrepo, scm, elastic-agent, secrets, package-repository].` 

I have placed the .jar file of plugin in plugins/external. I have followed all the steps mentioned [here](https://github.com/gocd-contrib/google-oauth-authorization-plugin/blob/master/INSTALL.md).
GoCD version : 19.5.0-9272

Is there anything else I should also considering while adding plugin. Any help will be appreciated!

**Comment by bdpiparva** [comment]
@erIamshivani  - The plugin id(`google.oauth.login`) shows that installed the plugin is `https://github.com/gocd-contrib/gocd-oauth-login` not the https://github.com/gocd-contrib/google-oauth-authorization-plugin.

Please, can you try installing the right plugin as suggested below -

1. Remove the existing plugin jar from the `external` directory
2. Download a stable jar from the https://github.com/gocd-contrib/google-oauth-authorization-plugin/releases and install it.
3. Restart the GoCD server.

**Comment by erIamshivani** [comment]
@bdpiparva Hey thanks that worked! 
Although I am now facing new error. I added 2 domains in Allowed Domains section, one is localhost and other was ip-address of server. However, now when I start server and head on to localhost, it gives me "Redirecting to Google" and then `400 Bad Request`. How can I change my settings, I am not able to go to dashboard?

**Comment by bdpiparva** [comment]
@erIamshivani  -  Allowed Domains is your google domain e.g. `gmail.com` or google provided business domain. You can not set it to localhost or IP address of the server. 

> "Redirecting to Google" and then 400 Bad Request. How can I change my settings, I am not able to go to dashboard

See if plugin logs have more details about the issue. See [doc](https://github.com/gocd-contrib/google-oauth-authorization-plugin/blob/master/INSTALL.md) for configuration details

**Comment by erIamshivani** [comment]
@bdpiparva  
Oh no! I am not able to solve it. There's no information related to this issue. I got confused since documentation wasn't clear. And I am totally new to GoCD. Can you please help?

**Comment by erIamshivani** [comment]
@bdpiparva 
I configured everything again. Yet it keeps me same error `Error: invalid_request 
device_id and device_name are required for private IP`. I am trying to use ip address and have mentioned that ip address in `authorised domains` in API credentials using `.xip.io` following my ip-address. 

Can someone help me?

**Comment by bdpiparva** [comment]
@erIamshivani - Please can you provide content of <authConfig> after removing the sensitive information.

Auth config xml is available under `Admin` >> `Config XML` menu.

**Comment by erIamshivani** [comment]
@bdpiparva 
When I **Add User**, as per guide, the page suggests me to refresh the current page. And when I do, it give be `Error 400 Bad request`. 
Although when I delete content between <security> tags in cruise-config.xml file located at `/etc/go`, then I can get access to dash board.

However following are the cruise-config.xml contents after removing sensitive information:

`<cruise xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="cruise-config.xsd" schemaVersion="124">
  <server artifactsdir="artifacts" siteUrl="http://<my-ip>:8153/go" secureSiteUrl="https://<my-ip>:8154/go" agentAutoRegisterKey="fba786bb-4d97-4bbf-b484-151c755ae7ad" webhookSecret="f0f1c2e7-234f-44b2-af6a-5a721a36072d" commandRepositoryLocation="default" serverId="eafa5054-03d1-4466-850f-6bb3fb3208c5" tokenGenerationKey="20d52d88-f908-44f7-b40f-e5d6ad29f4c6">
    <security>
      <authConfigs>
        <authConfig id="user1" pluginId="cd.go.authorization.google">
          <property>
            <key>ClientId</key>
          <encryptedValue>AES:**encrypted_value**</encryptedValue>
          </property>
          <property>
            <key>ClientSecret</key>
            <encryptedValue>AES:<<**encrypted_value**>></encryptedValue>
          </property>
          <property>
            <key>AllowedDomains</key>
            <value>https://mail.google.com
https://www.gmail.com/</value>
          </property>
        </authConfig>
      </authConfigs>
    </security>
  </server>
  <pipelines group="WithBash">
    <pipeline name="TestCase2">
      <materials>
        <git url="http://<my_ip>:8081/a/gocdtest" username="go" encryptedPassword="AES:<<>>encrypted_password" />
      </materials>
      <stage name="defaultStage">
        <jobs>
          <job name="BuildDeployTest">
            <tasks>
              <exec command="cat">
                <arg>cleanbuild.sh</arg>
              </exec>
            </tasks>
          </job>
"cruise-config.xml" 42L, 1936C`

------------------------------------------------
I get error as:
`Error 400 Bad request 
device_id and device_name are required for private IP: <my_ip>` , however there were no steps related to device_id and name mentioned anywhere.

**Comment by bdpiparva** [comment]
@bdpiparva - try changing allowed domains to `gmail.com`

```xml
<authConfig id="user1" pluginId="cd.go.authorization.google">
    <property>
        <key>ClientId</key>
        <encryptedValue>AES:**encrypted_value**</encryptedValue>
    </property>
    <property>
        <key>ClientSecret</key>
        <encryptedValue>AES: **encrypted_value**</encryptedValue>
    </property>
    <property>
        <key>AllowedDomains</key>
        <value>gmail.com</value>
    </property>
</authConfig>
```

**Comment by erIamshivani** [comment]
@bdpiparva 
I keep getting same error.
Can you give examples of **Authorized redirect URIs**? I have mentioned my ip address as `<ip_address>.xip.io` since it wasn't accepting my ip-address. 

I followed [these](773169666744-lhg7iane5qkv0ci9uolipa95516d8291.apps.googleusercontent.com) steps. Are you sure they work with GoCD version 19.6.0 too?

**Comment by bdpiparva** [comment]
Example authorization server URL: `http://<<your.go.server.hostname.or.ip>>/go/plugin/cd.go.authorization.google/authenticate`

Replace `<<your.go.server.hostname.or.ip>>` with your gocd server url.

**Comment by erIamshivani** [comment]
I mentioed the same thing. Still wont work. It doesn't accept ip address of server, that why I added `.xip.io` appending my ip-address. Do I have to explicitly configure endpoints, tokens?
