### ISSUE TITLE
authorization plugin not appearing

### ISSUE THREAD

**Issue by psandhu79** [gocd-contrib/google-oauth-authorization-plugin#6]
Hi

i have installed GoCD using helm and created a persisted volume and added the google oath plugin to the external folder

I enabled the filepassword auth however google outh plugin does not apper

in the logs i see

I 2018-06-29 11:57:59,697 ERROR [Thread-78] PluginSettingsMetadataLoader:65 - Plugin: google.oauth.login - Metadata load info: []

I 2018-06-29 11:57:59,696 ERROR [Thread-78] PluginSettingsMetadataLoader:64 - Failed to fetch plugin settings metadata for plugin google.oauth.login. Maybe the plugin does not implement plugin settings and view?

**Comment by bdpiparva** [comment]
> I 2018-06-29 11:57:59,697 ERROR [Thread-78] PluginSettingsMetadataLoader:65 - Plugin: google.oauth.login - Metadata load info: []

Looks like the plugin is already loaded by the gocd server.

Please, can you check if the plugin is listed under **_ Admin > Plugins_** page.

**Comment by psandhu79** [comment]
Thats what i assumed but cannot see the plugin

**Comment by originalgremlin** [comment]
Also having this problem.  Plugin is loaded but not appearing in the plugins list or auth dropdown.  Any idea what the problem was?

**Comment by bdpiparva** [comment]
Please can you provide the details about server version and the plugin version?

**Comment by originalgremlin** [comment]
My bad.  Copied the wrong plugin url to the google oauth plugin name.  Fixed the url and all is right with the world.

**Comment by bdpiparva** [comment]
Closing the issue.
