### ISSUE TITLE
Trying to login using OAuth 2.0 Client IDs Issue

### ISSUE THREAD

**Issue by MerNat** [gocd-contrib/google-oauth-authorization-plugin#81]
I'm currently facing an issue when trying to use this plugin with OAuth 2.0 Client IDs. It's just reloading and get back to let me log in again.

![Output when trying to login](https://i.imgur.com/H0nU148.png)

**Comment by joelsdc** [comment]
Hey, just FYI, I run into similar problems, seems something with latest builds. Give it another shot with google-oauth-authorization-plugin-3.0.0-19.jar, that one worked for me. I'm going to report this in another issue.

**Comment by MerNat** [comment]
@joelsdc Thanks.

**Comment by chadlwilson** [comment]
Closing on the assumption that this is fixed as it's stale. Please open an issue if there are issues with the latest plugin version.
